### ISSUE TITLE
Swagger does not work with latest releases

### ISSUE THREAD

**Issue by stemey** [wprl/baucis-example#5]
I updated the dependencies. The swagger module does not serve the docs at localhost:3333/api/api-docs

		"baucis-swagger": "1.0.0-prerelease.1",
		"baucis": "^1.0.0-candidate.12",
		"express": "^4.1.1",
		"mongoose": "~3.8.8"

I have similar problems with baucis-gform. There seems to be a change in how to add plugins.

**Comment by rickitan** [comment]
+1 it's not working for me

**Comment by wprl** [comment]
I think the problem is that the URL changed to `/api/documentation`.
